# Generated by Django 4.0.1 on 2022-01-16 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ssh',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=15, verbose_name='IP address')),
                ('name', models.CharField(max_length=32, verbose_name='Username')),
                ('password', models.CharField(max_length=32, verbose_name='Password')),
            ],
            options={
                'verbose_name': 'SSH connection',
                'verbose_name_plural': 'SSH connections',
            },
        ),
    ]
