# Generated by Django 4.0.1 on 2022-01-16 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ssh_client', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ssh',
            name='description',
            field=models.CharField(default='', max_length=250, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='ssh',
            name='hostname',
            field=models.CharField(default='', max_length=32, verbose_name='Hostname'),
        ),
        migrations.AlterField(
            model_name='ssh',
            name='ip',
            field=models.CharField(default='', max_length=15, verbose_name='IP address'),
        ),
        migrations.AlterField(
            model_name='ssh',
            name='name',
            field=models.CharField(default='', max_length=32, verbose_name='Username'),
        ),
        migrations.AlterField(
            model_name='ssh',
            name='password',
            field=models.CharField(default='', max_length=32, verbose_name='Password'),
        ),
    ]
