# Generated by Django 4.0.1 on 2022-01-16 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ssh_client', '0002_ssh_description_ssh_hostname_alter_ssh_ip_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ssh',
            old_name='name',
            new_name='username',
        ),
    ]
